### Pandas - DataFrame and Series
Pandas is a powerful data manipulation library, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. 
A Series is a one-dimensional array-like object, while DataFrame is a two dimensional, size-mutable and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

In [ ]:
import pandas as pd

In [5]:
## Series: Its a 1D array like object which can hold any data type
import pandas as pd

data = [1,2,3,4,5]
series = pd.Series(data)
print(series)
print(type(series))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [ ]:
## Create a Series from a Dictionary
data = {'a':1,'b':2,'c':3} #keys becomes default indexing
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [8]:
data = [10,20,30,40,50]
index = ['a','b','c','d','e']

pd.Series(data,index=index) # creating our own series with index

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [10]:
## DataFrame
## Creating a dataframe from a dictionary of list

data ={
    'Name': ['Tada','Ray','Aryan'],
    'Age':[24,23,22],
    'City':['NewYork','Tokyo','Delhi']
}

df = pd.DataFrame(data)
print(df)
print()
print(type(df))

    Name  Age     City
0   Tada   24  NewYork
1    Ray   23    Tokyo
2  Aryan   22    Delhi

<class 'pandas.DataFrame'>

In [11]:
import numpy as np
np.array(df)

array([['Tada', 24, 'NewYork'],
       ['Ray', 23, 'Tokyo'],
       ['Aryan', 22, 'Delhi']], dtype=object)

In [44]:
## Creating a DataFrame from a list of dictionaries 


import pandas as pd

data = [
    {'Name':'Tada','Age':21,'City':'Bhubaneswar','Salary':45000,'Department':'Data Science'},
    {'Name':'Ray','Age':23,'City':'Cuttack','Salary':52000,'Department':'AI'},
    {'Name':'Aryan','Age':22,'City':'Hanspal','Salary':48000,'Department':'Backend'},
    {'Name':'Neha','Age':24,'City':'Delhi','Salary':60000,'Department':'ML'},
    {'Name':'Riya','Age':25,'City':'Mumbai','Salary':65000,'Department':'Analytics'},
    {'Name':'Karan','Age':26,'City':'Bangalore','Salary':70000,'Department':'DevOps'}
]

df = pd.DataFrame(data)
print(df)

    Name  Age         City  Salary    Department
0   Tada   21  Bhubaneswar   45000  Data Science
1    Ray   23      Cuttack   52000            AI
2  Aryan   22      Hanspal   48000       Backend
3   Neha   24        Delhi   60000            ML
4   Riya   25       Mumbai   65000     Analytics
5  Karan   26    Bangalore   70000        DevOps

In [27]:
### Accessing data from DataFrame
df

    Name  Age         City  Salary    Department
0   Tada   21  Bhubaneswar   45000  Data Science
1    Ray   23      Cuttack   52000            AI
2  Aryan   22      Hanspal   48000       Backend
3   Neha   24        Delhi   60000            ML
4   Riya   25       Mumbai   65000     Analytics
5  Karan   26    Bangalore   70000        DevOps

In [28]:
df['Name'] #it now becomes a series

0     Tada
1      Ray
2    Aryan
3     Neha
4     Riya
5    Karan
Name: Name, dtype: str

In [31]:
df.loc[0,'Name'] #loc -> row index

'Tada'

In [20]:
df.iloc[0]  #-> index location

Name       Tada
Age          24
City    NewYork
Name: 0, dtype: object

In [33]:
## Accessing a specified element
int(df.at[1,'Age'])

23

In [34]:
df

    Name  Age         City  Salary    Department
0   Tada   21  Bhubaneswar   45000  Data Science
1    Ray   23      Cuttack   52000            AI
2  Aryan   22      Hanspal   48000       Backend
3   Neha   24        Delhi   60000            ML
4   Riya   25       Mumbai   65000     Analytics
5  Karan   26    Bangalore   70000        DevOps

In [35]:
print(df.at[3,'Age'])

24

In [37]:
### Accessing a specified element using iat

df.iat[2,2] #giving row and column index

'Hanspal'

In [ ]:
### Data manipulation with data frames
df

    Name  Age         City  Salary    Department
0   Tada   21  Bhubaneswar   45000  Data Science
1    Ray   23      Cuttack   52000            AI
2  Aryan   22      Hanspal   48000       Backend
3   Neha   24        Delhi   60000            ML
4   Riya   25       Mumbai   65000     Analytics
5  Karan   26    Bangalore   70000        DevOps

In [45]:
## Adding a new column
df['Car'] =  ['BMW','Audi','Volvo','Honda','Tesla','Ferrari']

In [46]:
df

    Name  Age         City  Salary    Department      Car
0   Tada   21  Bhubaneswar   45000  Data Science      BMW
1    Ray   23      Cuttack   52000            AI     Audi
2  Aryan   22      Hanspal   48000       Backend    Volvo
3   Neha   24        Delhi   60000            ML    Honda
4   Riya   25       Mumbai   65000     Analytics    Tesla
5  Karan   26    Bangalore   70000        DevOps  Ferrari

In [51]:
## Remove a column
df.drop('Car',axis=1,inplace=True)

In [52]:
df

    Name  Age         City  Salary    Department
0   Tada   21  Bhubaneswar   45000  Data Science
1    Ray   23      Cuttack   52000            AI
2  Aryan   22      Hanspal   48000       Backend
3   Neha   24        Delhi   60000            ML
4   Riya   25       Mumbai   65000     Analytics
5  Karan   26    Bangalore   70000        DevOps

In [53]:
### Add age to the column
df['Age'] = df['Age']+1

In [54]:
df

    Name  Age         City  Salary    Department
0   Tada   22  Bhubaneswar   45000  Data Science
1    Ray   24      Cuttack   52000            AI
2  Aryan   23      Hanspal   48000       Backend
3   Neha   25        Delhi   60000            ML
4   Riya   26       Mumbai   65000     Analytics
5  Karan   27    Bangalore   70000        DevOps

In [56]:
df.drop(0,inplace=True) #inplace makes the operation permanent

In [57]:
df

    Name  Age       City  Salary Department
1    Ray   24    Cuttack   52000         AI
2  Aryan   23    Hanspal   48000    Backend
3   Neha   25      Delhi   60000         ML
4   Riya   26     Mumbai   65000  Analytics
5  Karan   27  Bangalore   70000     DevOps

In [ ]:
df.head(2) #get the first 2

    Name  Age     City  Salary Department
1    Ray   24  Cuttack   52000         AI
2  Aryan   23  Hanspal   48000    Backend

In [60]:
df.describe() # Statistical summary of DataFrame

             Age        Salary
count   5.000000      5.000000
mean   25.000000  59000.000000
std     1.581139   9055.385138
min    23.000000  48000.000000
25%    24.000000  52000.000000
50%    25.000000  60000.000000
75%    26.000000  65000.000000
max    27.000000  70000.000000