### Data Manipulation and Analysis with Pandas
Data manipulation and analysis are key tasks in any data science or data analysis project. Pandas provides a wide range of functions for data manipulation and analysis making it easier to clean, transform and extract insights from data

In [1]:
import pandas as pd

## Creating a dummy csv file

In [2]:
import pandas as pd
import numpy as np

np.random.seed(42)

rows = 120

data = pd.DataFrame({
    "ID": range(1, rows + 1),
    "Name": [f"Person_{i}" for i in range(1, rows + 1)],
    "Age": np.random.randint(18, 60, rows),
    "City": np.random.choice(["Chennai", "Mumbai", "Delhi", "Bangalore", "Hyderabad", "Kolkata"], rows),
    "Salary": np.random.randint(25000, 120000, rows),
    "Experience_Years": np.random.randint(0, 20, rows),
    "Department": np.random.choice(["Data", "HR", "Finance", "Engineering", "Sales"], rows),
    "Performance_Score": np.round(np.random.uniform(1, 5, rows), 2)
})

data.to_csv("data.csv", index=False)

print("CSV file created successfully!")

CSV file created successfully!

In [4]:
df = pd.read_csv('data.csv')
 
#fetch the first 2 rows
df.head(2)

,ID,Name,Age,City,Salary,Experience_Years,Department,Performance_Score
0,1,Person_1,56,Mumbai,36411,9,Engineering,2.51
1,2,Person_2,46,Kolkata,27911,2,Finance,1.33

In [5]:
df

,ID,Name,Age,City,Salary,Experience_Years,Department,Performance_Score
0,1,Person_1,56,Mumbai,36411,9,Engineering,2.51
1,2,Person_2,46,Kolkata,27911,2,Finance,1.33
2,3,Person_3,32,Delhi,92270,7,Data,4.11
3,4,Person_4,25,Chennai,108763,13,Data,3.23
4,5,Person_5,38,Mumbai,33680,17,HR,2.70
...,...,...,...,...,...,...,...,...
115,116,Person_116,54,Delhi,35492,0,Data,1.06
116,117,Person_117,31,Bangalore,31102,0,Data,2.40
117,118,Person_118,20,Delhi,75336,18,Sales,3.36
118,119,Person_119,18,Mumbai,110314,10,Engineering,2.57
119,120,Person_120,22,Delhi,51641,4,Engineering,2.75

In [6]:
df.describe()

,ID,Age,Salary,Experience_Years,Performance_Score
count,120.000000,120.000000,120.000000,120.000000,120.000000
mean,60.500000,38.050000,68789.808333,9.350000,3.156750
std,34.785054,12.444735,28082.179573,6.142085,1.221182
min,1.000000,18.000000,25301.000000,0.000000,1.050000
25%,30.750000,26.000000,43680.500000,4.000000,2.135000
50%,60.500000,39.000000,69650.000000,9.500000,3.225000
75%,90.250000,50.000000,91835.000000,15.000000,4.267500
max,120.000000,59.000000,119660.000000,19.000000,5.000000

In [ ]:
df.dtypes

ID                     int64
Name                     str
Age                    int64
City                     str
Salary                 int64
Experience_Years       int64
Department               str
Performance_Score    float64
dtype: object

In [ ]:
## Handling Missing values
df.isnull().any(axis=1)

0      False
1      False
2      False
3      False
4      False
       ...
115    False
116    False
117    False
118    False
119    False
Length: 120, dtype: bool

In [11]:
df.isnull().sum()

ID                   0
Name                 0
Age                  0
City                 0
Salary               0
Experience_Years     0
Department           0
Performance_Score    0
dtype: int64

In [13]:
df_filled=df.fillna(0) #it will fill any missing value as 0

In [14]:
import pandas as pd
import numpy as np

np.random.seed(42)

rows = 120

data = pd.DataFrame({
    "ID": range(1, rows + 1),
    "Name": [f"Person_{i}" for i in range(1, rows + 1)],
    "Age": np.random.randint(18, 60, rows),
    "City": np.random.choice(["Chennai", "Mumbai", "Delhi", "Bangalore", "Hyderabad", "Kolkata"], rows),
    "Salary": np.random.randint(25000, 120000, rows),
    "Experience_Years": np.random.randint(0, 20, rows),
    "Department": np.random.choice(["Data", "HR", "Finance", "Engineering", "Sales"], rows),
    "Performance_Score": np.round(np.random.uniform(1, 5, rows), 2)
})

# Add missing values randomly
data.loc[np.random.choice(data.index, 10), "Age"] = np.nan
data.loc[np.random.choice(data.index, 8), "City"] = np.nan
data.loc[np.random.choice(data.index, 12), "Salary"] = np.nan
data.loc[np.random.choice(data.index, 6), "Performance_Score"] = np.nan

# Add some duplicate rows
data = pd.concat([data, data.iloc[5:10]])

# Shuffle dataset
data = data.sample(frac=1).reset_index(drop=True)

data.to_csv("messy_data.csv", index=False)

print("Messy dataset created!")

Messy dataset created!

In [16]:
df = pd.read_csv('messy_data.csv')
df

,ID,Name,Age,City,Salary,Experience_Years,Department,Performance_Score
0,97,Person_97,NaN,Delhi,81835.0,9,HR,3.47
1,81,Person_81,18.0,NaN,28436.0,18,Engineering,1.23
2,101,Person_101,26.0,Hyderabad,68484.0,19,Sales,3.08
3,24,Person_24,29.0,Bangalore,41371.0,19,Data,4.88
4,31,Person_31,32.0,Kolkata,97694.0,18,Sales,4.88
...,...,...,...,...,...,...,...,...
120,16,Person_16,39.0,Hyderabad,72254.0,6,Data,3.33
121,118,Person_118,20.0,Delhi,75336.0,18,Sales,3.36
122,75,Person_75,41.0,Delhi,70525.0,15,Finance,NaN
123,95,Person_95,22.0,Kolkata,99543.0,0,Engineering,1.91
124,80,Person_80,32.0,Delhi,72333.0,15,Sales,2.09

In [17]:
### filling missing values with the mean of the column
df['ExpYears_fillNa'] = df['Experience_Years'].fillna(df['Experience_Years'].mean())

In [19]:
df['City'].fillna(df['City'].mode()[0])

0          Delhi
1      Bangalore
2      Hyderabad
3      Bangalore
4        Kolkata
         ...
120    Hyderabad
121        Delhi
122        Delhi
123      Kolkata
124        Delhi
Name: City, Length: 125, dtype: str

In [20]:
print(df)

      ID        Name   Age       City   Salary  Experience_Years   Department  \
0     97   Person_97   NaN      Delhi  81835.0                 9           HR
1     81   Person_81  18.0        NaN  28436.0                18  Engineering
2    101  Person_101  26.0  Hyderabad  68484.0                19        Sales
3     24   Person_24  29.0  Bangalore  41371.0                19         Data
4     31   Person_31  32.0    Kolkata  97694.0                18        Sales
..   ...         ...   ...        ...      ...               ...          ...
120   16   Person_16  39.0  Hyderabad  72254.0                 6         Data
121  118  Person_118  20.0      Delhi  75336.0                18        Sales
122   75   Person_75  41.0      Delhi  70525.0                15      Finance
123   95   Person_95  22.0    Kolkata  99543.0                 0  Engineering
124   80   Person_80  32.0      Delhi  72333.0                15        Sales

     Performance_Score  ExpYears_fillNa
0                 3.47                9
1                 1.23               18
2                 3.08               19
3                 4.88               19
4                 4.88               18
..                 ...              ...
120               3.33                6
121               3.36               18
122                NaN               15
123               1.91                0
124               2.09               15

[125 rows x 9 columns]

In [21]:
pd.set_option('display.max_rows', None)
print(df)

      ID        Name   Age       City    Salary  Experience_Years  \
0     97   Person_97   NaN      Delhi   81835.0                 9
1     81   Person_81  18.0        NaN   28436.0                18
2    101  Person_101  26.0  Hyderabad   68484.0                19
3     24   Person_24  29.0  Bangalore   41371.0                19
4     31   Person_31  32.0    Kolkata   97694.0                18
5     86   Person_86  18.0  Hyderabad   55746.0                16
6     60   Person_60  35.0      Delhi  119179.0                 9
7    112  Person_112  44.0  Hyderabad   70236.0                19
8     76   Person_76  43.0    Chennai   44830.0                 6
9     54   Person_54  21.0    Kolkata   71975.0                 2
10    29   Person_29  45.0        NaN   54855.0                13
11    33   Person_33  54.0  Bangalore   32400.0                 1
12    44   Person_44  19.0    Chennai   57711.0                 7
13     6    Person_6  56.0     Mumbai       NaN                14
14    89   Person_89  28.0      Delhi   79045.0                 4
15    11   Person_11  41.0  Bangalore   62504.0                 7
16    10   Person_10  28.0        NaN   36111.0                16
17     6    Person_6  56.0     Mumbai       NaN                14
18    94   Person_94  50.0     Mumbai   65764.0                 3
19     9    Person_9  28.0      Delhi  113614.0                 1
20    53   Person_53  57.0      Delhi       NaN                14
21   105  Person_105  50.0    Kolkata   72202.0                 4
22   110  Person_110  57.0      Delhi   28420.0                 1
23    40   Person_40  42.0     Mumbai   84040.0                14
24   100  Person_100  24.0    Kolkata   43589.0                 1
25     8    Person_8  40.0  Hyderabad   96295.0                 9
26    30   Person_30   NaN  Hyderabad   86434.0                11
27    69   Person_69  31.0    Chennai       NaN                14
28    58   Person_58  21.0  Hyderabad   86135.0                12
29   109  Person_109  52.0  Bangalore   43711.0                15
30    77   Person_77  42.0  Hyderabad       NaN                 4
31    74   Person_74  35.0     Mumbai       NaN                 0
32    55   Person_55  19.0      Delhi   46357.0                 7
33    62   Person_62  51.0  Bangalore   63467.0                16
34    57   Person_57  59.0    Kolkata   27869.0                15
35   117  Person_117  31.0  Bangalore   31102.0                 0
36    41   Person_41  31.0  Bangalore   37183.0                10
37    20   Person_20  55.0  Hyderabad   55306.0                12
38    13   Person_13  57.0  Bangalore   33155.0                 8
39    65   Person_65  31.0    Chennai  111831.0                 8
40   108  Person_108  54.0    Chennai   58828.0                15
41    68   Person_68  25.0    Kolkata   47399.0                 0
42    98   Person_98   NaN      Delhi   98744.0                 4
43    66   Person_66  48.0  Bangalore       NaN                11
44    17   Person_17  19.0        NaN       NaN                 9
45    39   Person_39  21.0      Delhi   31295.0                 5
46    10   Person_10  28.0        NaN   36111.0                16
47   113  Person_113  52.0      Delhi   91235.0                11
48    37   Person_37  56.0    Kolkata   91690.0                19
49   115  Person_115  52.0  Bangalore   90726.0                 2
50    15   Person_15  20.0  Hyderabad   64384.0                15
51    64   Person_64  53.0    Kolkata  116412.0                 4
52    35   Person_35  38.0  Bangalore   40151.0                18
53    38   Person_38   NaN    Kolkata   29499.0                 9
54    18   Person_18  41.0  Hyderabad  110981.0                 2
55    87   Person_87  25.0    Chennai   74377.0                13
56    79   Person_79   NaN    Chennai  104909.0                11
57    43   Person_43  43.0    Kolkata       NaN                 0
58    91   Person_91  25.0     Mumbai   30600.0                15
59    23   Person_23  50.0    Kolkata  115735.0                12
60    85   Person_85  41.0    Kolkata   44738.0                14
61     3    Person_3  32.0      Delhi   92270.0                 7
62     7    Person_7  36.0  Bangalore  108879.0                 1
63   106  Person_106   NaN      Delhi   57635.0                12
64    72   Person_72  38.0  Bangalore   69064.0                 7
65    59   Person_59  46.0    Chennai   75108.0                17
66    71   Person_71  57.0  Bangalore   95271.0                15
67    88   Person_88   NaN    Chennai       NaN                19
68     2    Person_2  46.0    Kolkata   27911.0                 2
69    28   Person_28  59.0    Kolkata   45932.0                15
70    14   Person_14  41.0    Kolkata   98656.0                10
71   102  Person_102  25.0  Bangalore  107989.0                 9
72    83   Person_83  24.0     Mumbai  101213.0                13
73    52   Person_52   NaN    Chennai   27200.0                19
74   120  Person_120  22.0      Delhi   51641.0                 4
75     9    Person_9  28.0      Delhi  113614.0                 1
76    36   Person_36  26.0  Bangalore   76407.0                16
77    84   Person_84  26.0  Bangalore       NaN                 4
78    99   Person_99  45.0    Chennai   81491.0                 3
79    48   Person_48  25.0    Kolkata   73354.0                 6
80    63   Person_63   NaN      Delhi   48328.0                18
81   116  Person_116  54.0      Delhi   35492.0                 0
82    47   Person_47  24.0      Delhi   86267.0                 4
83    26   Person_26  42.0     Mumbai   27049.0                 7
84    73   Person_73  33.0    Kolkata   95091.0                12
85   111  Person_111  39.0    Kolkata   25301.0                16
86    45   Person_45  37.0    Chennai   30539.0                11
87    78   Person_78  58.0    Chennai   31893.0                 2
88    49   Person_49  52.0    Chennai   27557.0                 3
89    34   Person_34  24.0  Bangalore       NaN                 1
90    46   Person_46  45.0    Chennai   78351.0                11
91    90   Person_90  34.0    Kolkata   64790.0                11
92    12   Person_12  53.0  Hyderabad   26802.0                 0
93   103  Person_103  29.0     Mumbai   61212.0                18
94     1    Person_1  56.0     Mumbai   36411.0                 9
95    70   Person_70  40.0     Mumbai  111416.0                 1
96     7    Person_7  36.0  Bangalore  108879.0                 1
97    22   Person_22  38.0      Delhi   71843.0                 3
98   107  Person_107  41.0    Chennai       NaN                 3
99    42   Person_42  26.0    Chennai   54299.0                 4
100   92   Person_92  52.0  Hyderabad  119660.0                15
101   82   Person_82  42.0     Mumbai   99290.0                 4
102    5    Person_5  38.0        NaN   33680.0                17
103   21   Person_21  19.0      Delhi   41646.0                 6
104   19   Person_19  47.0  Bangalore   85713.0                17
105   51   Person_51  34.0        NaN  107018.0                12
106   61   Person_61  43.0     Mumbai  115272.0                18
107   50   Person_50  31.0  Bangalore   63360.0                 5
108   32   Person_32  20.0  Bangalore   68016.0                14
109   93   Person_93  52.0  Bangalore  118179.0                 6
110   27   Person_27  44.0  Hyderabad   56616.0                13
111  114  Person_114  18.0  Bangalore   79240.0                17
112   96   Person_96  59.0  Bangalore   70714.0                 4
113   67   Person_67  32.0    Chennai   83871.0                 0
114   25   Person_25  39.0     Mumbai  102371.0                 0
115   56   Person_56  23.0        NaN  102505.0                19
116  119  Person_119   NaN     Mumbai  110314.0                10
117  104  Person_104  51.0    Kolkata   68525.0                 0
118    4    Person_4  25.0        NaN  108763.0                13
119    8    Person_8  40.0  Hyderabad   96295.0                 9
120   16   Person_16  39.0  Hyderabad   72254.0                 6
121  118  Person_118  20.0      Delhi   75336.0                18
122   75   Person_75  41.0      Delhi   70525.0                15
123   95   Person_95  22.0    Kolkata   99543.0                 0
124   80   Person_80  32.0      Delhi   72333.0                15

      Department  Performance_Score  ExpYears_fillNa
0             HR               3.47                9
1    Engineering               1.23               18
2          Sales               3.08               19
3           Data               4.88               19
4          Sales               4.88               18
5             HR               3.22               16
6        Finance               4.29                9
7        Finance                NaN               19
8    Engineering               4.37                6
9           Data               3.14                2
10         Sales               1.30               13
11          Data               3.52                1
12   Engineering               3.48                7
13       Finance               4.63               14
14         Sales               4.40                4
15            HR               1.23                7
16   Engineering               2.87               16
17       Finance               4.63               14
18            HR               3.42                3
19         Sales               1.05                1
20          Data               3.79               14
21            HR               3.21                4
22         Sales               1.12                1
23          Data               2.12               14
24          Data               3.69                1
25         Sales               2.97                9
26       Finance               3.22               11
27   Engineering               2.51               14
28         Sales               1.65               12
29         Sales               1.54               15
30          Data               4.35                4
31         Sales               2.52                0
32          Data                NaN                7
33   Engineering               3.90               16
34          Data               3.74               15
35          Data               2.40                0
36       Finance               4.80               10
37            HR               4.47               12
38       Finance               1.47                8
39          Data               4.73                8
40            HR               2.61               15
41          Data               1.11                0
42            HR               2.43                4
43       Finance               4.46               11
44            HR               4.85                9
45         Sales               1.18                5
46   Engineering               2.87               16
47         Sales               3.82               11
48   Engineering               3.34               19
49   Engineering                NaN                2
50       Finance               3.98               15
51         Sales               2.67                4
52         Sales               2.82               18
53            HR               4.60                9
54         Sales               2.50                2
55            HR               4.08               13
56       Finance               2.66               11
57       Finance               2.82                0
58         Sales               2.80               15
59       Finance                NaN               12
60         Sales               4.99               14
61          Data               4.11                7
62   Engineering               1.44                1
63       Finance               3.24               12
64            HR               1.60                7
65       Finance               4.64               17
66       Finance               4.95               15
67            HR               4.78               19
68       Finance               1.33                2
69            HR               4.97               15
70            HR               3.60               10
71         Sales               4.09                9
72          Data               4.25               13
73       Finance               4.94               19
74   Engineering               2.75                4
75         Sales               1.05                1
76          Data               3.51               16
77         Sales               5.00                4
78   Engineering               1.45                3
79   Engineering               2.41                6
80   Engineering               3.45               18
81          Data               1.06                0
82         Sales               2.85                4
83            HR               4.56                7
84         Sales               3.38               12
85         Sales                NaN               16
86            HR               2.11               11
87   Engineering               2.87                2
88          Data               3.33                3
89         Sales               3.78                1
90          Data               1.75               11
91       Finance               1.99               11
92         Sales               1.48                0
93            HR               3.08               18
94   Engineering               2.51                9
95   Engineering               4.24                1
96   Engineering               1.44                1
97            HR               4.85                3
98            HR               4.51                3
99          Data               4.56                4
100      Finance               1.52               15
101        Sales               4.46                4
102           HR               2.70               17
103           HR               1.89                6
104           HR               2.14               17
105         Data               4.90               12
106         Data               4.80               18
107        Sales               1.31                5
108  Engineering               3.09               14
109      Finance               4.82                6
110        Sales               3.11               13
111         Data               1.85               17
112         Data               3.69                4
113  Engineering               1.18                0
114  Engineering               1.17                0
115  Engineering               4.26               19
116  Engineering               2.57               10
117         Data               4.41                0
118         Data               3.23               13
119        Sales               2.97                9
120         Data               3.33                6
121        Sales               3.36               18
122      Finance                NaN               15
123  Engineering               1.91                0
124        Sales               2.09               15

In [23]:
df.dtypes

ID                     int64
Name                     str
Age                  float64
City                     str
Salary               float64
Experience_Years       int64
Department               str
Performance_Score    float64
ExpYears_fillNa        int64
dtype: object

In [ ]:
## Renaming Columns
df=df.rename(columns={'Salary':'MoneyEarned'}) #it is given in key value pairs
print(df)

      ID        Name   Age       City  MoneyEarned  Experience_Years  \
0     97   Person_97   NaN      Delhi      81835.0                 9
1     81   Person_81  18.0        NaN      28436.0                18
2    101  Person_101  26.0  Hyderabad      68484.0                19
3     24   Person_24  29.0  Bangalore      41371.0                19
4     31   Person_31  32.0    Kolkata      97694.0                18
5     86   Person_86  18.0  Hyderabad      55746.0                16
6     60   Person_60  35.0      Delhi     119179.0                 9
7    112  Person_112  44.0  Hyderabad      70236.0                19
8     76   Person_76  43.0    Chennai      44830.0                 6
9     54   Person_54  21.0    Kolkata      71975.0                 2
10    29   Person_29  45.0        NaN      54855.0                13
11    33   Person_33  54.0  Bangalore      32400.0                 1
12    44   Person_44  19.0    Chennai      57711.0                 7
13     6    Person_6  56.0     Mumbai          NaN                14
14    89   Person_89  28.0      Delhi      79045.0                 4
15    11   Person_11  41.0  Bangalore      62504.0                 7
16    10   Person_10  28.0        NaN      36111.0                16
17     6    Person_6  56.0     Mumbai          NaN                14
18    94   Person_94  50.0     Mumbai      65764.0                 3
19     9    Person_9  28.0      Delhi     113614.0                 1
20    53   Person_53  57.0      Delhi          NaN                14
21   105  Person_105  50.0    Kolkata      72202.0                 4
22   110  Person_110  57.0      Delhi      28420.0                 1
23    40   Person_40  42.0     Mumbai      84040.0                14
24   100  Person_100  24.0    Kolkata      43589.0                 1
25     8    Person_8  40.0  Hyderabad      96295.0                 9
26    30   Person_30   NaN  Hyderabad      86434.0                11
27    69   Person_69  31.0    Chennai          NaN                14
28    58   Person_58  21.0  Hyderabad      86135.0                12
29   109  Person_109  52.0  Bangalore      43711.0                15
30    77   Person_77  42.0  Hyderabad          NaN                 4
31    74   Person_74  35.0     Mumbai          NaN                 0
32    55   Person_55  19.0      Delhi      46357.0                 7
33    62   Person_62  51.0  Bangalore      63467.0                16
34    57   Person_57  59.0    Kolkata      27869.0                15
35   117  Person_117  31.0  Bangalore      31102.0                 0
36    41   Person_41  31.0  Bangalore      37183.0                10
37    20   Person_20  55.0  Hyderabad      55306.0                12
38    13   Person_13  57.0  Bangalore      33155.0                 8
39    65   Person_65  31.0    Chennai     111831.0                 8
40   108  Person_108  54.0    Chennai      58828.0                15
41    68   Person_68  25.0    Kolkata      47399.0                 0
42    98   Person_98   NaN      Delhi      98744.0                 4
43    66   Person_66  48.0  Bangalore          NaN                11
44    17   Person_17  19.0        NaN          NaN                 9
45    39   Person_39  21.0      Delhi      31295.0                 5
46    10   Person_10  28.0        NaN      36111.0                16
47   113  Person_113  52.0      Delhi      91235.0                11
48    37   Person_37  56.0    Kolkata      91690.0                19
49   115  Person_115  52.0  Bangalore      90726.0                 2
50    15   Person_15  20.0  Hyderabad      64384.0                15
51    64   Person_64  53.0    Kolkata     116412.0                 4
52    35   Person_35  38.0  Bangalore      40151.0                18
53    38   Person_38   NaN    Kolkata      29499.0                 9
54    18   Person_18  41.0  Hyderabad     110981.0                 2
55    87   Person_87  25.0    Chennai      74377.0                13
56    79   Person_79   NaN    Chennai     104909.0                11
57    43   Person_43  43.0    Kolkata          NaN                 0
58    91   Person_91  25.0     Mumbai      30600.0                15
59    23   Person_23  50.0    Kolkata     115735.0                12
60    85   Person_85  41.0    Kolkata      44738.0                14
61     3    Person_3  32.0      Delhi      92270.0                 7
62     7    Person_7  36.0  Bangalore     108879.0                 1
63   106  Person_106   NaN      Delhi      57635.0                12
64    72   Person_72  38.0  Bangalore      69064.0                 7
65    59   Person_59  46.0    Chennai      75108.0                17
66    71   Person_71  57.0  Bangalore      95271.0                15
67    88   Person_88   NaN    Chennai          NaN                19
68     2    Person_2  46.0    Kolkata      27911.0                 2
69    28   Person_28  59.0    Kolkata      45932.0                15
70    14   Person_14  41.0    Kolkata      98656.0                10
71   102  Person_102  25.0  Bangalore     107989.0                 9
72    83   Person_83  24.0     Mumbai     101213.0                13
73    52   Person_52   NaN    Chennai      27200.0                19
74   120  Person_120  22.0      Delhi      51641.0                 4
75     9    Person_9  28.0      Delhi     113614.0                 1
76    36   Person_36  26.0  Bangalore      76407.0                16
77    84   Person_84  26.0  Bangalore          NaN                 4
78    99   Person_99  45.0    Chennai      81491.0                 3
79    48   Person_48  25.0    Kolkata      73354.0                 6
80    63   Person_63   NaN      Delhi      48328.0                18
81   116  Person_116  54.0      Delhi      35492.0                 0
82    47   Person_47  24.0      Delhi      86267.0                 4
83    26   Person_26  42.0     Mumbai      27049.0                 7
84    73   Person_73  33.0    Kolkata      95091.0                12
85   111  Person_111  39.0    Kolkata      25301.0                16
86    45   Person_45  37.0    Chennai      30539.0                11
87    78   Person_78  58.0    Chennai      31893.0                 2
88    49   Person_49  52.0    Chennai      27557.0                 3
89    34   Person_34  24.0  Bangalore          NaN                 1
90    46   Person_46  45.0    Chennai      78351.0                11
91    90   Person_90  34.0    Kolkata      64790.0                11
92    12   Person_12  53.0  Hyderabad      26802.0                 0
93   103  Person_103  29.0     Mumbai      61212.0                18
94     1    Person_1  56.0     Mumbai      36411.0                 9
95    70   Person_70  40.0     Mumbai     111416.0                 1
96     7    Person_7  36.0  Bangalore     108879.0                 1
97    22   Person_22  38.0      Delhi      71843.0                 3
98   107  Person_107  41.0    Chennai          NaN                 3
99    42   Person_42  26.0    Chennai      54299.0                 4
100   92   Person_92  52.0  Hyderabad     119660.0                15
101   82   Person_82  42.0     Mumbai      99290.0                 4
102    5    Person_5  38.0        NaN      33680.0                17
103   21   Person_21  19.0      Delhi      41646.0                 6
104   19   Person_19  47.0  Bangalore      85713.0                17
105   51   Person_51  34.0        NaN     107018.0                12
106   61   Person_61  43.0     Mumbai     115272.0                18
107   50   Person_50  31.0  Bangalore      63360.0                 5
108   32   Person_32  20.0  Bangalore      68016.0                14
109   93   Person_93  52.0  Bangalore     118179.0                 6
110   27   Person_27  44.0  Hyderabad      56616.0                13
111  114  Person_114  18.0  Bangalore      79240.0                17
112   96   Person_96  59.0  Bangalore      70714.0                 4
113   67   Person_67  32.0    Chennai      83871.0                 0
114   25   Person_25  39.0     Mumbai     102371.0                 0
115   56   Person_56  23.0        NaN     102505.0                19
116  119  Person_119   NaN     Mumbai     110314.0                10
117  104  Person_104  51.0    Kolkata      68525.0                 0
118    4    Person_4  25.0        NaN     108763.0                13
119    8    Person_8  40.0  Hyderabad      96295.0                 9
120   16   Person_16  39.0  Hyderabad      72254.0                 6
121  118  Person_118  20.0      Delhi      75336.0                18
122   75   Person_75  41.0      Delhi      70525.0                15
123   95   Person_95  22.0    Kolkata      99543.0                 0
124   80   Person_80  32.0      Delhi      72333.0                15

      Department  Performance_Score  ExpYears_fillNa
0             HR               3.47                9
1    Engineering               1.23               18
2          Sales               3.08               19
3           Data               4.88               19
4          Sales               4.88               18
5             HR               3.22               16
6        Finance               4.29                9
7        Finance                NaN               19
8    Engineering               4.37                6
9           Data               3.14                2
10         Sales               1.30               13
11          Data               3.52                1
12   Engineering               3.48                7
13       Finance               4.63               14
14         Sales               4.40                4
15            HR               1.23                7
16   Engineering               2.87               16
17       Finance               4.63               14
18            HR               3.42                3
19         Sales               1.05                1
20          Data               3.79               14
21            HR               3.21                4
22         Sales               1.12                1
23          Data               2.12               14
24          Data               3.69                1
25         Sales               2.97                9
26       Finance               3.22               11
27   Engineering               2.51               14
28         Sales               1.65               12
29         Sales               1.54               15
30          Data               4.35                4
31         Sales               2.52                0
32          Data                NaN                7
33   Engineering               3.90               16
34          Data               3.74               15
35          Data               2.40                0
36       Finance               4.80               10
37            HR               4.47               12
38       Finance               1.47                8
39          Data               4.73                8
40            HR               2.61               15
41          Data               1.11                0
42            HR               2.43                4
43       Finance               4.46               11
44            HR               4.85                9
45         Sales               1.18                5
46   Engineering               2.87               16
47         Sales               3.82               11
48   Engineering               3.34               19
49   Engineering                NaN                2
50       Finance               3.98               15
51         Sales               2.67                4
52         Sales               2.82               18
53            HR               4.60                9
54         Sales               2.50                2
55            HR               4.08               13
56       Finance               2.66               11
57       Finance               2.82                0
58         Sales               2.80               15
59       Finance                NaN               12
60         Sales               4.99               14
61          Data               4.11                7
62   Engineering               1.44                1
63       Finance               3.24               12
64            HR               1.60                7
65       Finance               4.64               17
66       Finance               4.95               15
67            HR               4.78               19
68       Finance               1.33                2
69            HR               4.97               15
70            HR               3.60               10
71         Sales               4.09                9
72          Data               4.25               13
73       Finance               4.94               19
74   Engineering               2.75                4
75         Sales               1.05                1
76          Data               3.51               16
77         Sales               5.00                4
78   Engineering               1.45                3
79   Engineering               2.41                6
80   Engineering               3.45               18
81          Data               1.06                0
82         Sales               2.85                4
83            HR               4.56                7
84         Sales               3.38               12
85         Sales                NaN               16
86            HR               2.11               11
87   Engineering               2.87                2
88          Data               3.33                3
89         Sales               3.78                1
90          Data               1.75               11
91       Finance               1.99               11
92         Sales               1.48                0
93            HR               3.08               18
94   Engineering               2.51                9
95   Engineering               4.24                1
96   Engineering               1.44                1
97            HR               4.85                3
98            HR               4.51                3
99          Data               4.56                4
100      Finance               1.52               15
101        Sales               4.46                4
102           HR               2.70               17
103           HR               1.89                6
104           HR               2.14               17
105         Data               4.90               12
106         Data               4.80               18
107        Sales               1.31                5
108  Engineering               3.09               14
109      Finance               4.82                6
110        Sales               3.11               13
111         Data               1.85               17
112         Data               3.69                4
113  Engineering               1.18                0
114  Engineering               1.17                0
115  Engineering               4.26               19
116  Engineering               2.57               10
117         Data               4.41                0
118         Data               3.23               13
119        Sales               2.97                9
120         Data               3.33                6
121        Sales               3.36               18
122      Finance                NaN               15
123  Engineering               1.91                0
124        Sales               2.09               15

In [27]:
## change datatypes
df['Age_new']=df['Age'].fillna(df['Age'].mean()).astype(float)

In [29]:
print(df)

      ID        Name   Age       City  MoneyEarned  Experience_Years  \
0     97   Person_97   NaN      Delhi      81835.0                 9
1     81   Person_81  18.0        NaN      28436.0                18
2    101  Person_101  26.0  Hyderabad      68484.0                19
3     24   Person_24  29.0  Bangalore      41371.0                19
4     31   Person_31  32.0    Kolkata      97694.0                18
5     86   Person_86  18.0  Hyderabad      55746.0                16
6     60   Person_60  35.0      Delhi     119179.0                 9
7    112  Person_112  44.0  Hyderabad      70236.0                19
8     76   Person_76  43.0    Chennai      44830.0                 6
9     54   Person_54  21.0    Kolkata      71975.0                 2
10    29   Person_29  45.0        NaN      54855.0                13
11    33   Person_33  54.0  Bangalore      32400.0                 1
12    44   Person_44  19.0    Chennai      57711.0                 7
13     6    Person_6  56.0     Mumbai          NaN                14
14    89   Person_89  28.0      Delhi      79045.0                 4
15    11   Person_11  41.0  Bangalore      62504.0                 7
16    10   Person_10  28.0        NaN      36111.0                16
17     6    Person_6  56.0     Mumbai          NaN                14
18    94   Person_94  50.0     Mumbai      65764.0                 3
19     9    Person_9  28.0      Delhi     113614.0                 1
20    53   Person_53  57.0      Delhi          NaN                14
21   105  Person_105  50.0    Kolkata      72202.0                 4
22   110  Person_110  57.0      Delhi      28420.0                 1
23    40   Person_40  42.0     Mumbai      84040.0                14
24   100  Person_100  24.0    Kolkata      43589.0                 1
25     8    Person_8  40.0  Hyderabad      96295.0                 9
26    30   Person_30   NaN  Hyderabad      86434.0                11
27    69   Person_69  31.0    Chennai          NaN                14
28    58   Person_58  21.0  Hyderabad      86135.0                12
29   109  Person_109  52.0  Bangalore      43711.0                15
30    77   Person_77  42.0  Hyderabad          NaN                 4
31    74   Person_74  35.0     Mumbai          NaN                 0
32    55   Person_55  19.0      Delhi      46357.0                 7
33    62   Person_62  51.0  Bangalore      63467.0                16
34    57   Person_57  59.0    Kolkata      27869.0                15
35   117  Person_117  31.0  Bangalore      31102.0                 0
36    41   Person_41  31.0  Bangalore      37183.0                10
37    20   Person_20  55.0  Hyderabad      55306.0                12
38    13   Person_13  57.0  Bangalore      33155.0                 8
39    65   Person_65  31.0    Chennai     111831.0                 8
40   108  Person_108  54.0    Chennai      58828.0                15
41    68   Person_68  25.0    Kolkata      47399.0                 0
42    98   Person_98   NaN      Delhi      98744.0                 4
43    66   Person_66  48.0  Bangalore          NaN                11
44    17   Person_17  19.0        NaN          NaN                 9
45    39   Person_39  21.0      Delhi      31295.0                 5
46    10   Person_10  28.0        NaN      36111.0                16
47   113  Person_113  52.0      Delhi      91235.0                11
48    37   Person_37  56.0    Kolkata      91690.0                19
49   115  Person_115  52.0  Bangalore      90726.0                 2
50    15   Person_15  20.0  Hyderabad      64384.0                15
51    64   Person_64  53.0    Kolkata     116412.0                 4
52    35   Person_35  38.0  Bangalore      40151.0                18
53    38   Person_38   NaN    Kolkata      29499.0                 9
54    18   Person_18  41.0  Hyderabad     110981.0                 2
55    87   Person_87  25.0    Chennai      74377.0                13
56    79   Person_79   NaN    Chennai     104909.0                11
57    43   Person_43  43.0    Kolkata          NaN                 0
58    91   Person_91  25.0     Mumbai      30600.0                15
59    23   Person_23  50.0    Kolkata     115735.0                12
60    85   Person_85  41.0    Kolkata      44738.0                14
61     3    Person_3  32.0      Delhi      92270.0                 7
62     7    Person_7  36.0  Bangalore     108879.0                 1
63   106  Person_106   NaN      Delhi      57635.0                12
64    72   Person_72  38.0  Bangalore      69064.0                 7
65    59   Person_59  46.0    Chennai      75108.0                17
66    71   Person_71  57.0  Bangalore      95271.0                15
67    88   Person_88   NaN    Chennai          NaN                19
68     2    Person_2  46.0    Kolkata      27911.0                 2
69    28   Person_28  59.0    Kolkata      45932.0                15
70    14   Person_14  41.0    Kolkata      98656.0                10
71   102  Person_102  25.0  Bangalore     107989.0                 9
72    83   Person_83  24.0     Mumbai     101213.0                13
73    52   Person_52   NaN    Chennai      27200.0                19
74   120  Person_120  22.0      Delhi      51641.0                 4
75     9    Person_9  28.0      Delhi     113614.0                 1
76    36   Person_36  26.0  Bangalore      76407.0                16
77    84   Person_84  26.0  Bangalore          NaN                 4
78    99   Person_99  45.0    Chennai      81491.0                 3
79    48   Person_48  25.0    Kolkata      73354.0                 6
80    63   Person_63   NaN      Delhi      48328.0                18
81   116  Person_116  54.0      Delhi      35492.0                 0
82    47   Person_47  24.0      Delhi      86267.0                 4
83    26   Person_26  42.0     Mumbai      27049.0                 7
84    73   Person_73  33.0    Kolkata      95091.0                12
85   111  Person_111  39.0    Kolkata      25301.0                16
86    45   Person_45  37.0    Chennai      30539.0                11
87    78   Person_78  58.0    Chennai      31893.0                 2
88    49   Person_49  52.0    Chennai      27557.0                 3
89    34   Person_34  24.0  Bangalore          NaN                 1
90    46   Person_46  45.0    Chennai      78351.0                11
91    90   Person_90  34.0    Kolkata      64790.0                11
92    12   Person_12  53.0  Hyderabad      26802.0                 0
93   103  Person_103  29.0     Mumbai      61212.0                18
94     1    Person_1  56.0     Mumbai      36411.0                 9
95    70   Person_70  40.0     Mumbai     111416.0                 1
96     7    Person_7  36.0  Bangalore     108879.0                 1
97    22   Person_22  38.0      Delhi      71843.0                 3
98   107  Person_107  41.0    Chennai          NaN                 3
99    42   Person_42  26.0    Chennai      54299.0                 4
100   92   Person_92  52.0  Hyderabad     119660.0                15
101   82   Person_82  42.0     Mumbai      99290.0                 4
102    5    Person_5  38.0        NaN      33680.0                17
103   21   Person_21  19.0      Delhi      41646.0                 6
104   19   Person_19  47.0  Bangalore      85713.0                17
105   51   Person_51  34.0        NaN     107018.0                12
106   61   Person_61  43.0     Mumbai     115272.0                18
107   50   Person_50  31.0  Bangalore      63360.0                 5
108   32   Person_32  20.0  Bangalore      68016.0                14
109   93   Person_93  52.0  Bangalore     118179.0                 6
110   27   Person_27  44.0  Hyderabad      56616.0                13
111  114  Person_114  18.0  Bangalore      79240.0                17
112   96   Person_96  59.0  Bangalore      70714.0                 4
113   67   Person_67  32.0    Chennai      83871.0                 0
114   25   Person_25  39.0     Mumbai     102371.0                 0
115   56   Person_56  23.0        NaN     102505.0                19
116  119  Person_119   NaN     Mumbai     110314.0                10
117  104  Person_104  51.0    Kolkata      68525.0                 0
118    4    Person_4  25.0        NaN     108763.0                13
119    8    Person_8  40.0  Hyderabad      96295.0                 9
120   16   Person_16  39.0  Hyderabad      72254.0                 6
121  118  Person_118  20.0      Delhi      75336.0                18
122   75   Person_75  41.0      Delhi      70525.0                15
123   95   Person_95  22.0    Kolkata      99543.0                 0
124   80   Person_80  32.0      Delhi      72333.0                15

      Department  Performance_Score  ExpYears_fillNa  Age_new
0             HR               3.47                9     37.8
1    Engineering               1.23               18     18.0
2          Sales               3.08               19     26.0
3           Data               4.88               19     29.0
4          Sales               4.88               18     32.0
5             HR               3.22               16     18.0
6        Finance               4.29                9     35.0
7        Finance                NaN               19     44.0
8    Engineering               4.37                6     43.0
9           Data               3.14                2     21.0
10         Sales               1.30               13     45.0
11          Data               3.52                1     54.0
12   Engineering               3.48                7     19.0
13       Finance               4.63               14     56.0
14         Sales               4.40                4     28.0
15            HR               1.23                7     41.0
16   Engineering               2.87               16     28.0
17       Finance               4.63               14     56.0
18            HR               3.42                3     50.0
19         Sales               1.05                1     28.0
20          Data               3.79               14     57.0
21            HR               3.21                4     50.0
22         Sales               1.12                1     57.0
23          Data               2.12               14     42.0
24          Data               3.69                1     24.0
25         Sales               2.97                9     40.0
26       Finance               3.22               11     37.8
27   Engineering               2.51               14     31.0
28         Sales               1.65               12     21.0
29         Sales               1.54               15     52.0
30          Data               4.35                4     42.0
31         Sales               2.52                0     35.0
32          Data                NaN                7     19.0
33   Engineering               3.90               16     51.0
34          Data               3.74               15     59.0
35          Data               2.40                0     31.0
36       Finance               4.80               10     31.0
37            HR               4.47               12     55.0
38       Finance               1.47                8     57.0
39          Data               4.73                8     31.0
40            HR               2.61               15     54.0
41          Data               1.11                0     25.0
42            HR               2.43                4     37.8
43       Finance               4.46               11     48.0
44            HR               4.85                9     19.0
45         Sales               1.18                5     21.0
46   Engineering               2.87               16     28.0
47         Sales               3.82               11     52.0
48   Engineering               3.34               19     56.0
49   Engineering                NaN                2     52.0
50       Finance               3.98               15     20.0
51         Sales               2.67                4     53.0
52         Sales               2.82               18     38.0
53            HR               4.60                9     37.8
54         Sales               2.50                2     41.0
55            HR               4.08               13     25.0
56       Finance               2.66               11     37.8
57       Finance               2.82                0     43.0
58         Sales               2.80               15     25.0
59       Finance                NaN               12     50.0
60         Sales               4.99               14     41.0
61          Data               4.11                7     32.0
62   Engineering               1.44                1     36.0
63       Finance               3.24               12     37.8
64            HR               1.60                7     38.0
65       Finance               4.64               17     46.0
66       Finance               4.95               15     57.0
67            HR               4.78               19     37.8
68       Finance               1.33                2     46.0
69            HR               4.97               15     59.0
70            HR               3.60               10     41.0
71         Sales               4.09                9     25.0
72          Data               4.25               13     24.0
73       Finance               4.94               19     37.8
74   Engineering               2.75                4     22.0
75         Sales               1.05                1     28.0
76          Data               3.51               16     26.0
77         Sales               5.00                4     26.0
78   Engineering               1.45                3     45.0
79   Engineering               2.41                6     25.0
80   Engineering               3.45               18     37.8
81          Data               1.06                0     54.0
82         Sales               2.85                4     24.0
83            HR               4.56                7     42.0
84         Sales               3.38               12     33.0
85         Sales                NaN               16     39.0
86            HR               2.11               11     37.0
87   Engineering               2.87                2     58.0
88          Data               3.33                3     52.0
89         Sales               3.78                1     24.0
90          Data               1.75               11     45.0
91       Finance               1.99               11     34.0
92         Sales               1.48                0     53.0
93            HR               3.08               18     29.0
94   Engineering               2.51                9     56.0
95   Engineering               4.24                1     40.0
96   Engineering               1.44                1     36.0
97            HR               4.85                3     38.0
98            HR               4.51                3     41.0
99          Data               4.56                4     26.0
100      Finance               1.52               15     52.0
101        Sales               4.46                4     42.0
102           HR               2.70               17     38.0
103           HR               1.89                6     19.0
104           HR               2.14               17     47.0
105         Data               4.90               12     34.0
106         Data               4.80               18     43.0
107        Sales               1.31                5     31.0
108  Engineering               3.09               14     20.0
109      Finance               4.82                6     52.0
110        Sales               3.11               13     44.0
111         Data               1.85               17     18.0
112         Data               3.69                4     59.0
113  Engineering               1.18                0     32.0
114  Engineering               1.17                0     39.0
115  Engineering               4.26               19     23.0
116  Engineering               2.57               10     37.8
117         Data               4.41                0     51.0
118         Data               3.23               13     25.0
119        Sales               2.97                9     40.0
120         Data               3.33                6     39.0
121        Sales               3.36               18     20.0
122      Finance                NaN               15     41.0
123  Engineering               1.91                0     22.0
124        Sales               2.09               15     32.0

In [30]:
df['Salary'] = df['MoneyEarned'].apply(lambda x:x*2)

In [31]:
df

,ID,Name,Age,City,MoneyEarned,Experience_Years,Department,Performance_Score,ExpYears_fillNa,Age_new,Salary
0,97,Person_97,NaN,Delhi,81835.0,9,HR,3.47,9,37.8,163670.0
1,81,Person_81,18.0,NaN,28436.0,18,Engineering,1.23,18,18.0,56872.0
2,101,Person_101,26.0,Hyderabad,68484.0,19,Sales,3.08,19,26.0,136968.0
3,24,Person_24,29.0,Bangalore,41371.0,19,Data,4.88,19,29.0,82742.0
4,31,Person_31,32.0,Kolkata,97694.0,18,Sales,4.88,18,32.0,195388.0
5,86,Person_86,18.0,Hyderabad,55746.0,16,HR,3.22,16,18.0,111492.0
6,60,Person_60,35.0,Delhi,119179.0,9,Finance,4.29,9,35.0,238358.0
7,112,Person_112,44.0,Hyderabad,70236.0,19,Finance,NaN,19,44.0,140472.0
8,76,Person_76,43.0,Chennai,44830.0,6,Engineering,4.37,6,43.0,89660.0
9,54,Person_54,21.0,Kolkata,71975.0,2,Data,3.14,2,21.0,143950.0
10,29,Person_29,45.0,NaN,54855.0,13,Sales,1.30,13,45.0,109710.0
11,33,Person_33,54.0,Bangalore,32400.0,1,Data,3.52,1,54.0,64800.0
12,44,Person_44,19.0,Chennai,57711.0,7,Engineering,3.48,7,19.0,115422.0
13,6,Person_6,56.0,Mumbai,NaN,14,Finance,4.63,14,56.0,NaN
14,89,Person_89,28.0,Delhi,79045.0,4,Sales,4.40,4,28.0,158090.0
15,11,Person_11,41.0,Bangalore,62504.0,7,HR,1.23,7,41.0,125008.0
16,10,Person_10,28.0,NaN,36111.0,16,Engineering,2.87,16,28.0,72222.0
17,6,Person_6,56.0,Mumbai,NaN,14,Finance,4.63,14,56.0,NaN
18,94,Person_94,50.0,Mumbai,65764.0,3,HR,3.42,3,50.0,131528.0
19,9,Person_9,28.0,Delhi,113614.0,1,Sales,1.05,1,28.0,227228.0
20,53,Person_53,57.0,Delhi,NaN,14,Data,3.79,14,57.0,NaN
21,105,Person_105,50.0,Kolkata,72202.0,4,HR,3.21,4,50.0,144404.0
22,110,Person_110,57.0,Delhi,28420.0,1,Sales,1.12,1,57.0,56840.0
23,40,Person_40,42.0,Mumbai,84040.0,14,Data,2.12,14,42.0,168080.0
24,100,Person_100,24.0,Kolkata,43589.0,1,Data,3.69,1,24.0,87178.0
25,8,Person_8,40.0,Hyderabad,96295.0,9,Sales,2.97,9,40.0,192590.0
26,30,Person_30,NaN,Hyderabad,86434.0,11,Finance,3.22,11,37.8,172868.0
27,69,Person_69,31.0,Chennai,NaN,14,Engineering,2.51,14,31.0,NaN
28,58,Person_58,21.0,Hyderabad,86135.0,12,Sales,1.65,12,21.0,172270.0
29,109,Person_109,52.0,Bangalore,43711.0,15,Sales,1.54,15,52.0,87422.0
30,77,Person_77,42.0,Hyderabad,NaN,4,Data,4.35,4,42.0,NaN
31,74,Person_74,35.0,Mumbai,NaN,0,Sales,2.52,0,35.0,NaN
32,55,Person_55,19.0,Delhi,46357.0,7,Data,NaN,7,19.0,92714.0
33,62,Person_62,51.0,Bangalore,63467.0,16,Engineering,3.90,16,51.0,126934.0
34,57,Person_57,59.0,Kolkata,27869.0,15,Data,3.74,15,59.0,55738.0
35,117,Person_117,31.0,Bangalore,31102.0,0,Data,2.40,0,31.0,62204.0
36,41,Person_41,31.0,Bangalore,37183.0,10,Finance,4.80,10,31.0,74366.0
37,20,Person_20,55.0,Hyderabad,55306.0,12,HR,4.47,12,55.0,110612.0
38,13,Person_13,57.0,Bangalore,33155.0,8,Finance,1.47,8,57.0,66310.0
39,65,Person_65,31.0,Chennai,111831.0,8,Data,4.73,8,31.0,223662.0
40,108,Person_108,54.0,Chennai,58828.0,15,HR,2.61,15,54.0,117656.0
41,68,Person_68,25.0,Kolkata,47399.0,0,Data,1.11,0,25.0,94798.0
42,98,Person_98,NaN,Delhi,98744.0,4,HR,2.43,4,37.8,197488.0
43,66,Person_66,48.0,Bangalore,NaN,11,Finance,4.46,11,48.0,NaN
44,17,Person_17,19.0,NaN,NaN,9,HR,4.85,9,19.0,NaN
45,39,Person_39,21.0,Delhi,31295.0,5,Sales,1.18,5,21.0,62590.0
46,10,Person_10,28.0,NaN,36111.0,16,Engineering,2.87,16,28.0,72222.0
47,113,Person_113,52.0,Delhi,91235.0,11,Sales,3.82,11,52.0,182470.0
48,37,Person_37,56.0,Kolkata,91690.0,19,Engineering,3.34,19,56.0,183380.0
49,115,Person_115,52.0,Bangalore,90726.0,2,Engineering,NaN,2,52.0,181452.0
50,15,Person_15,20.0,Hyderabad,64384.0,15,Finance,3.98,15,20.0,128768.0
51,64,Person_64,53.0,Kolkata,116412.0,4,Sales,2.67,4,53.0,232824.0
52,35,Person_35,38.0,Bangalore,40151.0,18,Sales,2.82,18,38.0,80302.0
53,38,Person_38,NaN,Kolkata,29499.0,9,HR,4.60,9,37.8,58998.0
54,18,Person_18,41.0,Hyderabad,110981.0,2,Sales,2.50,2,41.0,221962.0
55,87,Person_87,25.0,Chennai,74377.0,13,HR,4.08,13,25.0,148754.0
56,79,Person_79,NaN,Chennai,104909.0,11,Finance,2.66,11,37.8,209818.0
57,43,Person_43,43.0,Kolkata,NaN,0,Finance,2.82,0,43.0,NaN
58,91,Person_91,25.0,Mumbai,30600.0,15,Sales,2.80,15,25.0,61200.0
59,23,Person_23,50.0,Kolkata,115735.0,12,Finance,NaN,12,50.0,231470.0
60,85,Person_85,41.0,Kolkata,44738.0,14,Sales,4.99,14,41.0,89476.0
61,3,Person_3,32.0,Delhi,92270.0,7,Data,4.11,7,32.0,184540.0
62,7,Person_7,36.0,Bangalore,108879.0,1,Engineering,1.44,1,36.0,217758.0
63,106,Person_106,NaN,Delhi,57635.0,12,Finance,3.24,12,37.8,115270.0
64,72,Person_72,38.0,Bangalore,69064.0,7,HR,1.60,7,38.0,138128.0
65,59,Person_59,46.0,Chennai,75108.0,17,Finance,4.64,17,46.0,150216.0
66,71,Person_71,57.0,Bangalore,95271.0,15,Finance,4.95,15,57.0,190542.0
67,88,Person_88,NaN,Chennai,NaN,19,HR,4.78,19,37.8,NaN
68,2,Person_2,46.0,Kolkata,27911.0,2,Finance,1.33,2,46.0,55822.0
69,28,Person_28,59.0,Kolkata,45932.0,15,HR,4.97,15,59.0,91864.0
70,14,Person_14,41.0,Kolkata,98656.0,10,HR,3.60,10,41.0,197312.0
71,102,Person_102,25.0,Bangalore,107989.0,9,Sales,4.09,9,25.0,215978.0
72,83,Person_83,24.0,Mumbai,101213.0,13,Data,4.25,13,24.0,202426.0
73,52,Person_52,NaN,Chennai,27200.0,19,Finance,4.94,19,37.8,54400.0
74,120,Person_120,22.0,Delhi,51641.0,4,Engineering,2.75,4,22.0,103282.0
75,9,Person_9,28.0,Delhi,113614.0,1,Sales,1.05,1,28.0,227228.0
76,36,Person_36,26.0,Bangalore,76407.0,16,Data,3.51,16,26.0,152814.0
77,84,Person_84,26.0,Bangalore,NaN,4,Sales,5.00,4,26.0,NaN
78,99,Person_99,45.0,Chennai,81491.0,3,Engineering,1.45,3,45.0,162982.0
79,48,Person_48,25.0,Kolkata,73354.0,6,Engineering,2.41,6,25.0,146708.0
80,63,Person_63,NaN,Delhi,48328.0,18,Engineering,3.45,18,37.8,96656.0
81,116,Person_116,54.0,Delhi,35492.0,0,Data,1.06,0,54.0,70984.0
82,47,Person_47,24.0,Delhi,86267.0,4,Sales,2.85,4,24.0,172534.0
83,26,Person_26,42.0,Mumbai,27049.0,7,HR,4.56,7,42.0,54098.0
84,73,Person_73,33.0,Kolkata,95091.0,12,Sales,3.38,12,33.0,190182.0
85,111,Person_111,39.0,Kolkata,25301.0,16,Sales,NaN,16,39.0,50602.0
86,45,Person_45,37.0,Chennai,30539.0,11,HR,2.11,11,37.0,61078.0
87,78,Person_78,58.0,Chennai,31893.0,2,Engineering,2.87,2,58.0,63786.0
88,49,Person_49,52.0,Chennai,27557.0,3,Data,3.33,3,52.0,55114.0
89,34,Person_34,24.0,Bangalore,NaN,1,Sales,3.78,1,24.0,NaN
90,46,Person_46,45.0,Chennai,78351.0,11,Data,1.75,11,45.0,156702.0
91,90,Person_90,34.0,Kolkata,64790.0,11,Finance,1.99,11,34.0,129580.0
92,12,Person_12,53.0,Hyderabad,26802.0,0,Sales,1.48,0,53.0,53604.0
93,103,Person_103,29.0,Mumbai,61212.0,18,HR,3.08,18,29.0,122424.0
94,1,Person_1,56.0,Mumbai,36411.0,9,Engineering,2.51,9,56.0,72822.0
95,70,Person_70,40.0,Mumbai,111416.0,1,Engineering,4.24,1,40.0,222832.0
96,7,Person_7,36.0,Bangalore,108879.0,1,Engineering,1.44,1,36.0,217758.0
97,22,Person_22,38.0,Delhi,71843.0,3,HR,4.85,3,38.0,143686.0
98,107,Person_107,41.0,Chennai,NaN,3,HR,4.51,3,41.0,NaN
99,42,Person_42,26.0,Chennai,54299.0,4,Data,4.56,4,26.0,108598.0
100,92,Person_92,52.0,Hyderabad,119660.0,15,Finance,1.52,15,52.0,239320.0
101,82,Person_82,42.0,Mumbai,99290.0,4,Sales,4.46,4,42.0,198580.0
102,5,Person_5,38.0,NaN,33680.0,17,HR,2.70,17,38.0,67360.0
103,21,Person_21,19.0,Delhi,41646.0,6,HR,1.89,6,19.0,83292.0
104,19,Person_19,47.0,Bangalore,85713.0,17,HR,2.14,17,47.0,171426.0
105,51,Person_51,34.0,NaN,107018.0,12,Data,4.90,12,34.0,214036.0
106,61,Person_61,43.0,Mumbai,115272.0,18,Data,4.80,18,43.0,230544.0
107,50,Person_50,31.0,Bangalore,63360.0,5,Sales,1.31,5,31.0,126720.0
108,32,Person_32,20.0,Bangalore,68016.0,14,Engineering,3.09,14,20.0,136032.0
109,93,Person_93,52.0,Bangalore,118179.0,6,Finance,4.82,6,52.0,236358.0
110,27,Person_27,44.0,Hyderabad,56616.0,13,Sales,3.11,13,44.0,113232.0
111,114,Person_114,18.0,Bangalore,79240.0,17,Data,1.85,17,18.0,158480.0
112,96,Person_96,59.0,Bangalore,70714.0,4,Data,3.69,4,59.0,141428.0
113,67,Person_67,32.0,Chennai,83871.0,0,Engineering,1.18,0,32.0,167742.0
114,25,Person_25,39.0,Mumbai,102371.0,0,Engineering,1.17,0,39.0,204742.0
115,56,Person_56,23.0,NaN,102505.0,19,Engineering,4.26,19,23.0,205010.0
116,119,Person_119,NaN,Mumbai,110314.0,10,Engineering,2.57,10,37.8,220628.0
117,104,Person_104,51.0,Kolkata,68525.0,0,Data,4.41,0,51.0,137050.0
118,4,Person_4,25.0,NaN,108763.0,13,Data,3.23,13,25.0,217526.0
119,8,Person_8,40.0,Hyderabad,96295.0,9,Sales,2.97,9,40.0,192590.0
120,16,Person_16,39.0,Hyderabad,72254.0,6,Data,3.33,6,39.0,144508.0
121,118,Person_118,20.0,Delhi,75336.0,18,Sales,3.36,18,20.0,150672.0
122,75,Person_75,41.0,Delhi,70525.0,15,Finance,NaN,15,41.0,141050.0
123,95,Person_95,22.0,Kolkata,99543.0,0,Engineering,1.91,0,22.0,199086.0
124,80,Person_80,32.0,Delhi,72333.0,15,Sales,2.09,15,32.0,144666.0

In [32]:
## Data Aggregating and Grouping
grouped_mean =df.groupby('City')['MoneyEarned'].mean()

In [33]:
print(grouped_mean)

City
Bangalore    69430.954545
Chennai      62853.000000
Delhi        71745.428571
Hyderabad    76116.285714
Kolkata      67895.250000
Mumbai       78746.000000
Name: MoneyEarned, dtype: float64

In [38]:
grouped_sum=df.groupby(['City','Age'])['MoneyEarned'].sum()
print(grouped_sum)

City       Age
Bangalore  18.0     79240.0
           20.0     68016.0
           24.0         0.0
           25.0    107989.0
           26.0     76407.0
           29.0     41371.0
           31.0    131645.0
           36.0    217758.0
           38.0    109215.0
           41.0     62504.0
           47.0     85713.0
           48.0         0.0
           51.0     63467.0
           52.0    252616.0
           54.0     32400.0
           57.0    128426.0
           59.0     70714.0
Chennai    19.0     57711.0
           25.0     74377.0
           26.0     54299.0
           31.0    111831.0
           32.0     83871.0
           37.0     30539.0
           41.0         0.0
           43.0     44830.0
           45.0    159842.0
           46.0     75108.0
           52.0     27557.0
           54.0     58828.0
           58.0     31893.0
Delhi      19.0     88003.0
           20.0     75336.0
           21.0     31295.0
           22.0     51641.0
           24.0     86267.0
           28.0    306273.0
           32.0    164603.0
           35.0    119179.0
           38.0     71843.0
           41.0     70525.0
           52.0     91235.0
           54.0     35492.0
           57.0     28420.0
Hyderabad  18.0     55746.0
           20.0     64384.0
           21.0     86135.0
           26.0     68484.0
           39.0     72254.0
           40.0    192590.0
           41.0    110981.0
           42.0         0.0
           44.0    126852.0
           52.0    119660.0
           53.0     26802.0
           55.0     55306.0
Kolkata    21.0     71975.0
           22.0     99543.0
           24.0     43589.0
           25.0    120753.0
           32.0     97694.0
           33.0     95091.0
           34.0     64790.0
           39.0     25301.0
           41.0    143394.0
           43.0         0.0
           46.0     27911.0
           50.0    187937.0
           51.0     68525.0
           53.0    116412.0
           56.0     91690.0
           59.0     73801.0
Mumbai     24.0    101213.0
           25.0     30600.0
           29.0     61212.0
           35.0         0.0
           39.0    102371.0
           40.0    111416.0
           42.0    210379.0
           43.0    115272.0
           50.0     65764.0
           56.0     36411.0
Name: MoneyEarned, dtype: float64

In [41]:
## aggregate multiple functions

grouped_agg = df.groupby('City')['Age'].agg(['mean','sum','count'])
print(grouped_agg)

                mean    sum  count
City
Bangalore  39.160000  979.0     25
Chennai    39.000000  585.0     15
Delhi      33.722222  607.0     18
Hyderabad  38.214286  535.0     14
Kolkata    40.200000  804.0     20
Mumbai     41.357143  579.0     14

In [ ]:
## Merging and Joining Dataframes

In [3]:
import pandas as pd

df1 = pd.DataFrame({
    "EmpID": [1,2,3,4,5],
    "Name": ["Alice","Bob","Charlie","David","Eva"],
    "Department": ["Data","HR","Engineering","Data","Finance"]
})

print(df1)

   EmpID     Name   Department
0      1    Alice         Data
1      2      Bob           HR
2      3  Charlie  Engineering
3      4    David         Data
4      5      Eva      Finance

In [4]:
df2 = pd.DataFrame({
    "EmpID": [1,2,3,6],
    "Salary": [50000,45000,70000,60000],
    "City": ["Chennai","Mumbai","Delhi","Bangalore"]
})

print(df2)

   EmpID  Salary       City
0      1   50000    Chennai
1      2   45000     Mumbai
2      3   70000      Delhi
3      6   60000  Bangalore

In [5]:
## Merge DataFrame on the 'Key Columns'
pd.merge(df1,df2,on="EmpID",how="inner")

   EmpID     Name   Department  Salary     City
0      1    Alice         Data   50000  Chennai
1      2      Bob           HR   45000   Mumbai
2      3  Charlie  Engineering   70000    Delhi

In [6]:
pd.merge(df1,df2,on="EmpID",how="outer")

   EmpID     Name   Department   Salary       City
0      1    Alice         Data  50000.0    Chennai
1      2      Bob           HR  45000.0     Mumbai
2      3  Charlie  Engineering  70000.0      Delhi
3      4    David         Data      NaN        NaN
4      5      Eva      Finance      NaN        NaN
5      6      NaN          NaN  60000.0  Bangalore

In [48]:
pd.merge(df1,df2,on="EmpID",how="left")

   EmpID     Name   Department   Salary     City
0      1    Alice         Data  50000.0  Chennai
1      2      Bob           HR  45000.0   Mumbai
2      3  Charlie  Engineering  70000.0    Delhi
3      4    David         Data      NaN      NaN
4      5      Eva      Finance      NaN      NaN

In [7]:
pd.merge(df1,df2,on="EmpID",how="right")

   EmpID     Name   Department  Salary       City
0      1    Alice         Data   50000    Chennai
1      2      Bob           HR   45000     Mumbai
2      3  Charlie  Engineering   70000      Delhi
3      6      NaN          NaN   60000  Bangalore